# Generated by Django 4.1.13 on 2024-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('Organization_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
