# Generated by Django 4.1.13 on 2024-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
